version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: konnectservices
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: konnectservices
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "${PWD}/sql/seed.sql:/sql/seed.sql"
    restart: always

  flyway:
      image: flyway/flyway:9.3-alpine
      command: -url=jdbc:postgresql://postgres:5432/konnectservices -user=konnectservices -connectRetries=10 migrate
      volumes:
          - "${PWD}/sql/migrations:/flyway/sql"
      depends_on:
          - postgres