version: '3.8'
services:

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: service_db
      POSTGRES_USER: myuser
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
